version: '3.8'

services:
  w2m-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
     - SPRING_PROFILES_ACTIVE=default
     - SPRING_RABBITMQ_HOST=rabbitmq
    volumes:
      - ./data:/workspace/data
    depends_on:
      - h2-database
      - rabbitmq

  h2-database:
    image: buildo/h2database
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      - H2_OPTIONS=-ifNotExists

  rabbitmq:
    image: rabbitmq:3.13.2-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
